SERVER_PORT : 7020

server:
  port: ${SERVER_PORT}

spring:
  application:
    name: be-core-storage-app
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

#tracing
management:
  tracing:
    enabled : true
    sampling:
      probability: 1.0


springdoc:
  api-docs:
    enabled: true
    path: /api/storage/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/storage/swagger-ui.html