name: Deploy Maven Package
 
on:
  push:
    # branches:
    #   - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: maven
          server-id: github
 
      - name: Build and Deploy
        run: |
          pwd
          ls -al
          echo "-----------------Maven version-----------------"
          mvn -v
          echo "-----------------------------------------------"
          mvn -B clean deploy -pl ${service_name}-sdk -Dmaven.test.skip=true -s settings.xml
          # mvn -B clean deploy -N -Dmaven.test.skip=true
          echo "-----------------------------------------------"
        env:
          service_name: "be-core-storage"
          GITHUB_USER: ${{ github.actor}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


 